name: deploy_app

on: 
  # push:
  #   paths:
  #     - infrastructure/**
  #   branches:
  #     - main
  workflow_dispatch

env:
  SUBSCRIPTION_ID: ''
  TENANT_ID: ''
  RG_NAME: 'aks-golang-application'
  CLUSTER_NAME: 'aks-golang-application'

jobs:
  create-cluster:
    name: 'create kube cluster for app'
    env:
      ARM_CLIENT_ID: ${{ secrets.SVC_KUBE_CLIENTID }}
      ARM_CLIENT_SECRET: ${{ secrets.SVC_KUBE_CLIENTSECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1.2.1 

    - name: Terraform Format
      id: fmt
      run: |
        ls
        cd infrastructure
        terraform fmt -list=true -diff

    - name: Terraform Init
      id: init
      run: |
        cd infrastructure
        # terraform init -backend-config=configs/backend.tfvars.json
        terraform init
    
    - name: Terraform Validate
      id: validate
      run: |
        cd infrastructure
        terraform validate -json  

    - name: Terraform Apply
      id: apply  
      run:  |
        cd infrastructure
        terraform apply -var-file=configs/infrstructure.tfvars.json --auto-approve
        
  deploy-app:
    name: 'deploy app to the cluster'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 

    - name: Get AKS credentials
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          set -euo pipefail

          az login --service-principal -u ${{ secrets.SVC_KUBE_CLIENTID }} -p ${{ secrets.SVC_KUBE_CLIENTSECRET }} --tenant ${{ secrets.TENANT_ID }}
          az account set -s ${{ secrets.SUBSCRIPTION_ID }}
          az account show            
          az aks get-credentials --resource-group ${{ env.RG_NAME }} --name ${{ env.CLUSTER_NAME }}            
            
    - uses: Azure/setup-kubectl@v1

    - name: Apply Secret Provider Class
      id: secret_driver
      run: |
        ls
        cd deployment
        kubectl apply -f secretproviderclass.yaml
    
    - name: Apply app deployment
      id: deployment
      run: |
        cd deployment
        kubectl apply -f golang-app.yaml
        
    - name: Apply app service
      id: service
      run: |
        cd deployment
        kubectl apply -f golang-service.yaml
        
       
    
